# docker-compose.yml (Final Recommended Version)

version: '3.8'

services:
  redis:
    image: "redis:7.2-alpine"
    container_name: aios-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aios-web
    ports:
      - "8765:8765"
    env_file:
      - ./python-backend/.env
    volumes:
      - ./python-backend:/app
    depends_on:
      - redis
      - sandbox-manager

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aios-flower
    # --- FINAL FIX: The command is now simpler ---
    # Because app.py now configures the celery object on import,
    # we don't need to specify the broker here anymore.
    command: ["celery", "-A", "app.celery", "flower"]
    ports:
      - "5555:5555"
    env_file:
      - ./python-backend/.env
    depends_on:
      - redis
      - web

  sandbox-manager:
    build:
      context: .
      dockerfile: sandbox_manager/Dockerfile
    container_name: aios-sandbox-manager
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  redis_data: