# render.yaml (Revised for External Sandbox)
# This file defines the services for the AI-OS backend to be deployed on Render.

services:
  # 1. The Redis Service
  # Using a paid plan is recommended for stability and more memory.
  - type: redis
    name: aios-redis
    plan: starter # Upgrade from 'free' for better performance.
    ipAllowList: [] # Allows services in your Render account to connect.

  # 2. The Web Service (Gunicorn + Flask/Socket.IO)
  # CRITICAL: You must upgrade this service's plan in the Render Dashboard.
  # The 'free' plan (512MB RAM) is not enough.
  - type: web
    name: aios-web
    plan: starter # REQUIRED: Select a plan with at least 1GB RAM.
    runtime: docker
    repo: https://github.com/GodBoii/AI-OS
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    # The CMD from your Dockerfile is used by default.
    envVars:
      # Link to the Environment Group containing all your secrets.
      - fromGroup: aios-secrets

  # 3. The AI Worker Service (Celery)
  # CRITICAL: This service must also be upgraded to a plan with more RAM.
  - type: worker
    name: aios-worker
    plan: starter # REQUIRED: Select a plan with at least 1GB RAM.
    runtime: docker
    repo: https://github.com/GodBoii/AI-OS
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    # Override the CMD to run the celery worker.
    # Reduced concurrency to 2 to conserve memory on smaller plans.
    dockerCommand: "celery -A app.celery worker --loglevel=info --concurrency=2"
    envVars:
      # Link to the Environment Group containing all your secrets.
      - fromGroup: aios-secrets

  # 4. Flower Monitoring Service (Optional but Recommended)
  # This is lightweight and can often run on the free plan.
  - type: web
    name: aios-flower
    plan: free
    runtime: docker
    repo: https://github.com/GodBoii/AI-OS
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    # The broker URL is pulled from the environment group.
    dockerCommand: "celery -A app.celery flower --broker=$REDIS_URL"
    envVars:
      # Link to the Environment Group containing all your secrets.
      - fromGroup: aios-secrets
