# render.yaml (Final Version with Corrected YAML Syntax)
services:
  - type: redis
    name: aios-redis
    plan: free
    ipAllowList: []

  - type: web
    name: aios-web
    plan: free
    runtime: docker
    repo: https://github.com/GodBoii/AI-OS
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    # ===================================================================
    # CRITICAL FIX: The entire command is now in one set of double quotes
    # with no nested quotes around the app factory call.
    dockerCommand: "gunicorn --worker-class eventlet -w 1 --timeout 300 --keep-alive 65 --bind 0.0.0.0:$PORT app:create_app()"
    # ===================================================================
    envVars:
      - fromGroup: aios-secrets
      - key: REDIS_URL
        fromService:
          type: redis
          name: aios-redis
          property: connectionString

  - type: web
    name: aios-flower
    plan: free
    runtime: docker
    repo: https://github.com/GodBoii/AI-OS
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: "celery -A app.celery flower --broker=$REDIS_URL"
    envVars:
      - fromGroup: aios-secrets
      - key: REDIS_URL
        fromService:
          type: redis
          name: aios-redis
          property: connectionString