# render.yaml (Final Version with All Fixes)
services:
  - type: redis
    name: aios-redis
    plan: free
    ipAllowList: []

  - type: web
    name: aios-web
    plan: free
    runtime: docker
    repo: https://github.com/GodBoii/AI-OS
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: "gunicorn --worker-class eventlet -w 1 --timeout 300 --keep-alive 65 --bind 0.0.0.0:$PORT app:app"
    envVars:
      - fromGroup: aios-secrets

  - type: web # Must be 'web' for the free tier
    name: aios-worker
    plan: free
    runtime: docker
    repo: https://github.com/GodBoii/AI-OS
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    # ===================================================================
    # CRITICAL FIX: Explicitly tell Celery to use the Redis URL
    # from the environment variable provided by Render.
    dockerCommand: "celery -A app.celery worker --loglevel=info --concurrency=1 --broker=$REDIS_URL"
    # ===================================================================
    envVars:
      - fromGroup: aios-secrets

  - type: web
    name: aios-flower
    plan: free
    runtime: docker
    repo: https://github.com/GodBoii/AI-OS
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: "celery -A app.celery flower --broker=$REDIS_URL"
    envVars:
      - fromGroup: aios-secrets