# render.yaml (Optimized for Render's Free Tier)

services:
  # 1. The Redis Service
  - type: redis
    name: aios-redis
    plan: free # Use the free Redis plan
    ipAllowList: [] 

  # 2. The Web Service (Gunicorn + Flask/Socket.IO)
  - type: web
    name: aios-web
    plan: free # Target the 512MB free plan
    runtime: docker
    repo: https://github.com/GodBoii/AI-OS
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    # CRITICAL FIX: Override the Dockerfile's CMD to force only 1 worker
    dockerCommand: "gunicorn --worker-class eventlet -w 1 --timeout 300 --keep-alive 65 --bind 0.0.0.0:$PORT app:app"
    envVars:
      - fromGroup: aios-secrets

  # 3. The AI Worker Service (Celery)
  - type: worker
    name: aios-worker
    plan: free # Target the 512MB free plan
    runtime: docker
    repo: https://github.com/GodBoii/AI-OS
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    # Concurrency is already correctly set to 1
    dockerCommand: "celery -A app.celery worker --loglevel=info --concurrency=1"
    envVars:
      - fromGroup: aios-secrets

  # 4. Flower Monitoring Service (Optional)
  - type: web
    name: aios-flower
    plan: free
    runtime: docker
    repo: https://github.com/GodBoii/AI-OS
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: "celery -A app.celery flower --broker=$REDIS_URL"
    envVars:
      - fromGroup: aios-secrets