# render.yaml (Final Version - Simplified for Eventlet Architecture)
services:
  - type: redis
    name: aios-redis
    plan: free
    ipAllowList: []

  - type: web
    name: aios-web
    plan: free
    runtime: docker
    repo: https://github.com/GodBoii/AI-OS
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
        dockerCommand: "gunicorn --worker-class eventlet -w 1 --timeout 300 --keep-alive 65 --bind 0.0.0.0:$PORT 'app:create_app()'"
    envVars:
      - fromGroup: aios-secrets
      - key: REDIS_URL
        fromService:
          type: redis
          name: aios-redis
          property: connectionString

  - type: web
    name: aios-flower
    plan: free
    runtime: docker
    repo: https://github.com/GodBoii/AI-OS
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: "celery -A app.celery flower --broker=$REDIS_URL"
    envVars:
      - fromGroup: aios-secrets
      - key: REDIS_URL
        fromService:
          type: redis
          name: aios-redis
          property: connectionString  