# render.yaml (Final Corrected Version)
services:
  - type: redis
    name: aios-redis
    plan: free
    ipAllowList: []

  - type: web
    name: aios-web
    plan: free # Target the 512MB free plan
    runtime: docker
    repo: https://github.com/GodBoii/AI-OS
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    # ===================================================================
    # CRITICAL FIX HERE: This line was missing. It forces Gunicorn
    # to use only ONE worker, overriding the Dockerfile's default of 4.
    dockerCommand: "gunicorn --worker-class eventlet -w 1 --timeout 300 --keep-alive 65 --bind 0.0.0.0:$PORT app:app"
    # ===================================================================
    envVars:
      - fromGroup: aios-secrets

  - type: worker
    name: aios-worker
    plan: free # Target the 512MB free plan
    runtime: docker
    repo: https://github.com/GodBoii/AI-OS
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: "celery -A app.celery worker --loglevel=info --concurrency=1"
    envVars:
      - fromGroup: aios-secrets

  - type: web
    name: aios-flower
    plan: free
    runtime: docker
    repo: https://github.com/GodBoii/AI-OS
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: "celery -A app.celery flower --broker=$REDIS_URL"
    envVars:
      - fromGroup: aios-secrets